### ISSUE TITLE
Link rendering not working for ResponseEntity<ResourceSupport>in version 0.2.2

### ISSUE THREAD

**Issue by thiagogarbazza** [osvaldopina/linkbuilder#1]
## What versions you are using?

- jvm version: _1.7_
- spring version: _4.1.7-RELEASE_
- linkbuilder version: _0.2.2_

## What's the problem?

**Method:**
```java
@EnableSelfFromCurrentCall
@GenerateUriTemplateFor(rel = "app.some-method")
@Links({@Link(destination = RootRestController.class, rel = "app.root")})
@RequestMapping(method = GET, value = "/some-method")
public ResponseEntity<T extends ResourceSupport> someMethod() {
    return new ResponseEntity<>(new ResourceSupport(), HttpStatus.OK);
}
```

**StackTrace:**
```java
com.github.osvaldopina.linkbuilder.LinkBuilderException: The payload must be a org.springframework.hateoas.Resource but it was org.springframework.http.ResponseEntity
	at com.github.osvaldopina.linkbuilder.methodtemplate.urigenerator.impl.SpringLinkAnnotatedMethodUriGeneratorImpl.generate(SpringLinkAnnotatedMethodUriGeneratorImpl.java:60) ~[linkbuilder-0.2.2.jar:na]
	at com.github.osvaldopina.linkbuilder.direct.impl.LinksToResourceMethodInterceptor.afterReturning(LinksToResourceMethodInterceptor.java:46) ~[linkbuilder-0.2.2.jar:na]
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:53) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at br.gov.bcb.crd.restadapter.controller.ExcecaoRestController$$EnhancerBySpringCGLIB$$a4b94fad.detalhar(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
	at br.gov.bcb.crd.restadapter.controller.ExcecaoRestController$$FastClassBySpringCGLIB$$c86c0d71.invoke(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at br.gov.bcb.crd.restadapter.controller.ExcecaoRestController$$EnhancerBySpringCGLIB$$ab5d9d06.detalhar(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:88) ~[na:1.7.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.7.0]
	at java.lang.reflect.Method.invoke(Method.java:613) ~[na:2.6 (04-22-2013)]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.1.7.RELEASE.jar:4.1.7.RELEASE]
```

**Comment by osvaldopina** [comment]
fixed in 0.2.3
